#!/bin/bash
Size=256
Delta=1
Orientations=8
Scales=8
ThetaSigma=0.1
ScaleSigma=0.1
MaxScale=128
DeltaLog=0.1
Tao=20
Trails=48000
MaxTrails=4800
PhiFreqs=10
RhoFreqs=5
ThetaFreqs=10
ScaleFreqs=5
InitDist="[(-30,0,30,1.5),(30,0,330,1.5)]"
HistFileName=${ThetaSigma}_${ScaleSigma}_${MaxScale}_${Tao}_${PhiFreqs}_${RhoFreqs}_${ThetaFreqs}_${ScaleFreqs}.dat
HistPath=output/app/GreensFunctionFourierCoefficients/${HistFileName}
Threads=48
time stack test :STCFourierSeries-test --test-arguments "${Size} ${Delta} ${Orientations} ${Scales} ${ThetaSigma} ${ScaleSigma} ${MaxScale} ${DeltaLog} ${Tao}  ${Trails} ${MaxTrails} ${PhiFreqs} ${RhoFreqs} ${ThetaFreqs} ${ScaleFreqs} ${InitDist} ${HistPath} ${Threads} +RTS -N${Threads} -RTS"
