#!/bin/bash
Size=128
Orientations=16
Scales=16
ThetaSigma=0.1
ScaleSigma=0.2
MaxScale=32
Tao=100
Trails=1000000
MaxTrails=10000
ThetaFreqs=10
ScaleFreqs=8
HollowRadius=4
CutoffRadius=32
HistFileName=${Size}_${ThetaSigma}_${ScaleSigma}_${MaxScale}_${Tao}_${ThetaFreqs}_${ScaleFreqs}.dat  
HistPath=output/test/STCR2Z2T0S0PointSetBinary/${HistFileName}
FilterFileFolder=/holding_disk/Pinwheel
NumInteration=20
WriteSourceFlag=True
SaveEdgeDataFlag=True
LoadEdgeDataFlag=False
Circle="(Circle{circleNum=8,circleRadius=35})"
Shape2D="Points(0,0)2${Circle}"
UseFFTWWisdomFlag=True
FFTWWisdomFileName="fftwWisdom.dat"
BatchSize=6
Threads=6

time stack test :STCR2Z2T0S0PointSetBinary-test --test-arguments "${Size} ${Orientations} ${Scales} ${ThetaSigma} ${ScaleSigma} ${MaxScale} ${Tao}  ${Trails} ${MaxTrails} ${ThetaFreqs} ${ScaleFreqs} ${HollowRadius} ${CutoffRadius} ${HistPath} ${FilterFileFolder} ${NumInteration} ${WriteSourceFlag} ${SaveEdgeDataFlag} ${LoadEdgeDataFlag} ${Shape2D} ${UseFFTWWisdomFlag} ${FFTWWisdomFileName} ${BatchSize} ${Threads} +RTS -N${Threads} -RTS" # --ghc-options -j8
