#!/bin/bash
Size=512
Orientations=16
Scales=16
ThetaSigma=0.1
ScaleSigma=0.1
MaxScale=64
Tao=100
Trails=1000000
MaxTrails=10000
ThetaFreqs=8
ScaleFreqs=6
HollowRadius=4
CutoffRadius=64
HistFileName=${Size}_${ThetaSigma}_${ScaleSigma}_${MaxScale}_${Tao}_${ThetaFreqs}_${ScaleFreqs}.dat  
HistPath=output/test/STCR2Z2T0S0EdgeBinary/${HistFileName}
FilterFileFolder=/holding_disk/Pinwheel
NumInteration=40
WriteSourceFlag=True
SaveEdgeDataFlag=True
LoadEdgeDataFlag=False
EdgeFile=output/test/STCR2Z2T0S0Edge/avocados1.edge
NumNoisePoint=100
S=1
UseFFTWWisdomFlag=True
FFTWWisdomFileName="fftwWisdom.dat"
BatchSize=6
Threads=6

time stack test :STCR2Z2T0S0EdgeBinary-test --test-arguments "${Size} ${Orientations} ${Scales} ${ThetaSigma} ${ScaleSigma} ${MaxScale} ${Tao}  ${Trails} ${MaxTrails} ${ThetaFreqs} ${ScaleFreqs} ${HollowRadius} ${CutoffRadius} ${HistPath} ${FilterFileFolder} ${NumInteration} ${WriteSourceFlag} ${SaveEdgeDataFlag} ${LoadEdgeDataFlag} ${EdgeFile} ${NumNoisePoint} ${S} ${UseFFTWWisdomFlag} ${FFTWWisdomFileName} ${BatchSize} ${Threads} +RTS -N${Threads} -RTS" #--ghc-options -j8
