name:                Stochastic-Completion-Field
version:             0.1.0.0
github:              "XinhuaZhang/Stochastic-Completion-Field"
license:             BSD3
author:              "Xinhua Zhang"
maintainer:          "xinhua@unm.edu"
copyright:           "Copyright: (c) 2019 Xinhua Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Computer Vision

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/XinhuaZhang/Stochastic-Completion-Field#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.3.0 && < 0.6.0.0
- binary >= 0.8.6.0 && < 0.9.0.0
- bytestring >= 0.10.8.2 &&  < 0.11
- conduit >= 1.3.1 && < 1.4.0
- conduit-extra >= 1.3.1 && < 1.4.0
- containers >= 0.6.0.1 && < 0.7.0.0
- deepseq >= 1.4.3.0 && < 1.5.0.0
- directory >= 1.3.3.0 && < 1.4.0.0
- dlist >= 0.8.0.5 && < 1.0
- filepath >= 1.4.2.1 && < 1.5.0.0
- gnuplot >= 0.5.6 && < 0.6
- JuicyPixels >= 3.3.3 && < 4.0.0
- hashable >= 1.2.7.0 && < 1.3.0.0
- hmatrix >= 0.19.0.0 && < 0.20.0.0
- monad-parallel >= 0.7.2.3 && < 0.8.0.0
- mwc-random >= 0.14.0.0 && < 0.15.0.0
# - opencv >= 0.0.2.1 && < 0.1
- parallel >= 3.2.2.0 && < 4.0.0.0
- random >= 1.1 && < 2.0
- repa >= 3.4.1.4 && < 3.5.0.0
- resourcet >= 1.2.2
- statistics >= 0.15.0.0 && < 0.16.0.0
- text >= 1.2.3.1 && < 1.3.0.0
- time == 1.8.0.2
- unordered-containers >= 0.2.9.0 && < 0.3.0.0
- vector >= 0.12.0.2 && < 0.13.0.0

library:
  source-dirs: src

executables:
  PlotGreensFunctionR2S1-exe:
    main:                PlotGreensFunctionR2S1.hs
    source-dirs:         app/FokkerPlanckMonteCarlo/PlotGreensFunctionR2S1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is PlotGreensFunctionR2S1
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    dependencies:
    - Stochastic-Completion-Field
  PlotGreensFunctionR2S1RP-exe:
    main:                PlotGreensFunctionR2S1RP.hs
    source-dirs:         app/FokkerPlanckMonteCarlo/PlotGreensFunctionR2S1RP
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is PlotGreensFunctionR2S1RP
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    dependencies:
    - Stochastic-Completion-Field
  # PlotGreensFunctionR2S1T0-exe:
  #   main:                PlotGreensFunctionR2S1T0.hs
  #   source-dirs:         app/FokkerPlanckMonteCarlo/PlotGreensFunctionR2S1T0
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   - -O2
  #   - -j4
  #   - -main-is PlotGreensFunctionR2S1T0
  #   - -fno-liberate-case
  #   - -funfolding-use-threshold1000
  #   - -funfolding-keeness-factor1000
  #   #- -fllvm
  #   #- -optlo-O3
  #   dependencies:
  #   - Stochastic-Completion-Field
  # PlotGreensFunctionR2Z1T0-exe:
  #   main:                PlotGreensFunctionR2Z1T0.hs
  #   source-dirs:         app/FokkerPlanckMonteCarlo/PlotGreensFunctionR2Z1T0
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   - -O2
  #   - -j4
  #   - -main-is PlotGreensFunctionR2Z1T0
  #   - -fno-liberate-case
  #   - -funfolding-use-threshold1000
  #   - -funfolding-keeness-factor1000
  #   #- -fllvm
  #   #- -optlo-O3
  #   dependencies:
  #   - Stochastic-Completion-Field
  # PlotGreensFunctionR2Z2T0S0-exe:
  #   main:                PlotGreensFunctionR2Z2T0S0.hs
  #   source-dirs:         app/FokkerPlanckMonteCarlo/PlotGreensFunctionR2Z2T0S0
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   - -O2
  #   - -j4
  #   - -main-is PlotGreensFunctionR2Z2T0S0
  #   - -fno-liberate-case
  #   - -funfolding-use-threshold1000
  #   - -funfolding-keeness-factor1000
  #   #- -fllvm
  #   #- -optlo-O3
  #   dependencies:
  #   - Stochastic-Completion-Field

tests:
  R2Z1T0ToR2S1T0-test:
    main:                R2Z1T0ToR2S1T0.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is R2Z1T0ToR2S1T0
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    dependencies:
    - Stochastic-Completion-Field
  R2Z2T0S0ToR2S1RPT0S0-test:
    main:                R2Z2T0S0ToR2S1RPT0S0.hs
    source-dirs:         test/R2Z2T0S0ToR2S1RPT0S0
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is R2Z2T0S0ToR2S1RPT0S0
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    dependencies:
    - Stochastic-Completion-Field
  STCR2S1-test:
    main:                STCR2S1.hs
    source-dirs:         test/STCR2S1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2S1
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2S1PointSet-test:
    main:                STCR2S1PointSet.hs
    source-dirs:         test/STCR2S1PointSet
    ghc-options:
    - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2S1PointSet
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2S1Image-test:
    main:                STCR2S1Image.hs
    source-dirs:         test/STCR2S1Image
    ghc-options:
    - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2S1Image
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2S1Edge-test:
    main:                STCR2S1Edge.hs
    source-dirs:         test/STCR2S1Edge
    ghc-options:
    - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2S1Edge
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z1T0-test:
    main:                STCR2Z1T0.hs
    source-dirs:         test/STCR2Z1T0
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z1T0
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z1T0_1-test:
    main:                STCR2Z1T0_1.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z1T0_1
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z1T0Image-test:
    main:                STCR2Z1T0Image.hs
    source-dirs:         test/STCR2Z1T0Image
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -j4
    - -main-is STCR2Z1T0Image
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z1T0PointSet-test:
    main:                STCR2Z1T0PointSet.hs
    source-dirs:         test/STCR2Z1T0PointSet
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z1T0PointSet
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z1T0Edge-test:
    main:                STCR2Z1T0Edge.hs
    source-dirs:         test/STCR2Z1T0Edge
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z1T0Edge
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z1T0ImageSparseCode-test:
    main:                STCR2Z1T0ImageSparseCode.hs
    source-dirs:         test/STCR2Z1T0ImageSparseCode
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z1T0ImageSparseCode
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0-test:
    main:                STCR2Z2T0S0.hs
    source-dirs:         test/STCR2Z2T0S0
    ghc-options:
    - -threaded
    - -rtsopts
    # - -with-rtsopts=-K64m
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0PointSet-test:
    main:                STCR2Z2T0S0PointSet.hs
    source-dirs:         test/STCR2Z2T0S0PointSet
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0PointSet
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0ReversalCornerPointSet-test:
    main:                STCR2Z2T0S0ReversalCornerPointSet.hs
    source-dirs:         test/STCR2Z2T0S0ReversalCornerPointSet
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0ReversalCornerPointSet
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0KoffkaCross-test:
    main:                STCR2Z2T0S0KoffkaCross.hs
    source-dirs:         test/STCR2Z2T0S0KoffkaCross
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0KoffkaCross
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0Image-test:
    main:                STCR2Z2T0S0Image.hs
    source-dirs:         test/STCR2Z2T0S0Image
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0Image
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0Edge-test:
    main:                STCR2Z2T0S0Edge.hs
    source-dirs:         test/STCR2Z2T0S0Edge
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0Edge
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0EndPoint-test:
    main:                STCR2Z2T0S0EndPoint.hs
    source-dirs:         test/STCR2Z2T0S0EndPoint
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0EndPoint
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # - -fllvm
    # - -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0Amodal-test:
    main:                STCR2Z2T0S0Amodal.hs
    source-dirs:         test/STCR2Z2T0S0Amodal
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0Amodal
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    #- -fllvm
    #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  STCR2Z2T0S0EndModal-test:
    main:                STCR2Z2T0S0EndModal.hs
    source-dirs:         test/STCR2Z2T0S0EndModal
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is STCR2Z2T0S0EndModal
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  Resize-test:
    main:                Resize.hs
    source-dirs:         test/Resize
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is Resize
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    dependencies:
    - Stochastic-Completion-Field
  OrientationAnalysis-test:
    main:                OrientationAnalysis.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is OrientationAnalysis
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  EquivarianceDiagram-test:
    main:                EquivarianceDiagram.hs
    source-dirs:         test/EquivarianceDiagram
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j4
    - -main-is EquivarianceDiagram
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  RadialPhase-test:
    main:                RadialPhase.hs
    source-dirs:         test/RadialPhase
    ghc-options:
    - -threaded
    - -rtsopts
    # - -with-rtsopts=-K64m
    - -O2
    - -j4
    - -main-is RadialPhase
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # #- -fllvm
    # #- -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    dependencies:
    - Stochastic-Completion-Field
  CannyEdgeEndPoint-test:
    main:                CannyEdgeEndPoint.hs
    source-dirs:         test/CannyEdgeEndPoint
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -j4
    - -main-is CannyEdgeEndPoint
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    # - -fllvm
    # - -optlo-O3
    extra-libraries:
    - stdc++
    - lapack
    - gomp
    - fftw3
    - fftw3f
    - fftw3l
    - m
    # - opencv_imgcodecs
    # - opencv_core
    # - opencv_features2d
    # - opencv_highgui
    # - opencv_calib3d
    # - opencv_imgcodecs
    # - opencv_photo
    # - opencv_video
    # - opencv_imgproc
    # - opencv_videoio
    dependencies:
    - Stochastic-Completion-Field